# Generated by Django 3.2.13 on 2022-11-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BossCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poster_path', models.CharField(max_length=200)),
                ('attack_damage', models.IntegerField()),
                ('hp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poster_path', models.CharField(max_length=200)),
                ('attack_damage', models.IntegerField()),
                ('hp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BossSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=100)),
                ('skill_range', models.IntegerField()),
                ('skill_comment', models.CharField(default='이 카드는 평범한 카드입니다...', max_length=100)),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviecards.bosscards')),
            ],
        ),
    ]
